version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build-image:
    docker:
      - image: cimg/go:1.17.2
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: "invalid-ecr-build-sample"

workflows:
  main:
    jobs:
      - build-image:
          context: 
            - test
