version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build-image:
    docker:
      - image: circleci/golang:1.17.2
    steps:
      - checkout
      - aws-ecr/build-image:
          region: ap-northeast-1
          tag: "$CIRCLE_SHA1"
          repo: "invalid-ecr-build-sample"

workflows:
  main:
    jobs:
      - build-image:
          context: 
            - test
